name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Run separate type-check for Jest and Cypress
      - name: Type Check Jest
        run: npm run type-check:jest

      - name: Type Check Cypress
        run: npm run type-check:cypress

      - name: Run unit tests (Jest)
        run: npm run test:ci

      - name: Run Cypress tests
        run: npm run cypress:run
